apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mbm149/ArgoCD_test.git
    targetRevision: HEAD
    path: ss
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
