apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
  name: myapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx
        name: myapp
        ports:
        - containerPort: 8080
        resources: {}
status: {}
