apiVersion: apps/v1.2
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nanajanashia/argocd-app:1.2
        name: nginx
        ports:
        - containerPort: 8080
